version: '2'

services:
  image: node:11
  volumes:
    - .:/usr/src/service/
  working_dir: /usr/src/service/
  install:
    extends:
      service: base
      command: yarn install
  build:
    extends:
      service: base
      command: yarn build
  create-bundles:
    extends:
      service: base
      command: yarn create-bundles

