version: "3"

services:

  app:
    image: node
    volumes:
      - ./:/app
    working_dir: /app
    depends_on: 
      - mongoDB
    environment: 
      NODE_ENV: Development
    ports:
      - ${PORT}:${PORT}
    command: yarn dev

  mongoDB:
    image: mongo
    expose:
      - ${DB_PORT}
    volumes:
      - ./data/db:/data/db